### ISSUE TITLE
I want to use Inline Style in the component but it doesn't work

### ISSUE THREAD

**Issue by tareq-rezk** [ArunMichaelDsouza/react-image-appear#12]

**Comment by ArunMichaelDsouza** [comment]
You can use the [className](https://github.com/ArunMichaelDsouza/react-image-appear#classname-string) prop to add custom styling.

**Comment by tareq-rezk** [comment]
I want to style the element in the state,
so I want to add inline style it's required 
is there any way ??

**Comment by ArunMichaelDsouza** [comment]
There is no support for a ``style`` prop as such but I think the ``className`` prop should work in the same manner.
