### ISSUE TITLE
Images loaded, loader doesn't disappear.

### ISSUE THREAD

**Issue by nuriofernandez** [ArunMichaelDsouza/react-image-appear#14]
Hi! I have a problem with this component. the loading gif/placeholder isn't disappearing once the image has loaded.

My steps:
- Web loads.
- Async content API request starts.
- When the content is ready, creates a few ReactImageAppear elements with the API provided src.
- Loader gif appears.
- When the image loads, it's placed behind the loader gif.
- Loading gif doesn't disappear.

**Comment by mikkybang** [comment]
I have this same issue too

**Comment by Stranger65536** [comment]
+1 for me

**Comment by didaquis** [comment]
+1 for me

**Comment by ArunMichaelDsouza** [comment]
Hi, can you please provide a demo link using codepen or codesandbox so that I can debug the issue. Or maybe the steps to replicate it. Thanks!

**Comment by didaquis** [comment]
Hi @ArunMichaelDsouza 

[bug-react-image-appear.zip](https://github.com/ArunMichaelDsouza/react-image-appear/files/4683217/bug-react-image-appear.zip)

Observe the file: `bug-react-image-appear/src/components/CartViewerItem/index.js`

**Comment by ArunMichaelDsouza** [comment]
Fix now available in [v1.3.24](https://github.com/ArunMichaelDsouza/react-image-appear/releases/tag/v1.3.24).
