### ISSUE TITLE
onClick prop is not passed down to the <img> element

### ISSUE THREAD

**Issue by pcw0002** [ArunMichaelDsouza/react-image-appear#15]
I was trying to pass an onClick prop down to the underlying <img> element, but looking through the code it looks like the onClick prop is never destructured and passed down. Are there any plans in the future to implement this? I'm happy to open a PR for it if needed.

**Comment by ArunMichaelDsouza** [comment]
Hi @pcw0002, yeah it would be great to have a PR for this. Please feel free to create one. Thanks!

**Comment by pcw0002** [comment]
Thank you! I'll open one now and close this issue
