### ISSUE TITLE
Placeholder shows underneath image after image is loaded

### ISSUE THREAD

**Issue by xaphod** [ArunMichaelDsouza/react-image-appear#20]
See screenshot. 
Fixed in https://github.com/ArunMichaelDsouza/react-image-appear/pull/19

<img width="191" alt="Screen Shot 2020-08-24 at 7 40 15 AM" src="https://user-images.githubusercontent.com/3776302/91040989-36e91700-e5dd-11ea-97bf-55610d83440b.png">

**Comment by ArunMichaelDsouza** [comment]
Hi @xaphod, thank you for the fix. It's now available in [v1.3.26](https://github.com/ArunMichaelDsouza/react-image-appear/releases/tag/v1.3.26).
