### ISSUE TITLE
loader icon shows

### ISSUE THREAD

**Issue by moparlakci** [ArunMichaelDsouza/react-image-appear#6]
Sometimes it shows the loader icon when the image is already loaded.

caching issue maybe?

**Comment by psambit9791** [comment]
Facing same issue. Any updates?

**Comment by omnibrain** [comment]
I'm also facing this issue. Please help?

**Comment by psambit9791** [comment]
I decided against using the loader icon. No work around yet.

**Comment by ArunMichaelDsouza** [comment]
Hi, can someone please share a demo link using codepen or codesandbox so that I can debug the issue. Or maybe the steps to replicate it. Thanks!

**Comment by marcindCP** [comment]
any solution ?

**Comment by Skyball** [comment]
The same issue when refreshing.

**Comment by crypteriumguy** [comment]
Haha the same issue.

**Comment by davidramos-om** [comment]
Same issue, but on chrome for android and desktop Firefox

**Comment by hahatulk** [comment]
the same issue

**Comment by didaquis** [comment]
Related issue: https://github.com/ArunMichaelDsouza/react-image-appear/issues/14

**Comment by ArunMichaelDsouza** [comment]
Fix now available in [v1.3.24](https://github.com/ArunMichaelDsouza/react-image-appear/releases/tag/v1.3.24).
