### ISSUE TITLE
How do you dimension this?

### ISSUE THREAD

**Issue by jordangrant** [ArunMichaelDsouza/react-image-appear#7]
I'm new to ReactJS but I found this component incredibly difficult to style (the resulting image). Might be helpful to add to the readme how to style the image, I could not figure it out so I'm using the regular <img/>

**Comment by ArunMichaelDsouza** [comment]
Hi @jordangrant, you can use the ``className`` prop that has been recently added to [v1.2.22](https://github.com/ArunMichaelDsouza/react-image-appear/releases/tag/v1.2.22).
