### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by rufat** [ArunMichaelDsouza/react-image-appear#8]
When I try to build, it says:
```
Failed to minify the code from this file:
        ./node_modules/react-image-appear/src/ReactImageAppear.js:16
```

**React version: 16.8.3**
**React scripts: 2.1.1**

![image](https://user-images.githubusercontent.com/5330471/71087390-7db48080-21b5-11ea-96bb-dc86b7675e3d.png)

**Comment by ArunMichaelDsouza** [comment]
Hi @oop, I tried importing the library in a fresh [CRA](https://github.com/facebook/create-react-app) based project and it seems to be building fine. Might be something to do with your build pipeline setup.
